# Discord Knowledge Bot Configuration

# Bot Configuration
bot:
  prefix: "!"
  intents:
    message_content: true
    guilds: true
    messages: true

# OpenAI Configuration (for chat only)
openai:
  model: "gpt-4o-mini"
  max_tokens: 1000
  temperature: 0.7

# Local Embeddings Configuration
embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

# ChromaDB Configuration
chromadb:
  persist_directory: "./data"
  collection_name: "discord_knowledge"

# Indexing Configuration
indexing:
  chunk_size: 1000
  max_messages_per_request: 100
  rate_limit_delay: 1.0 